#!/bin/bash
# Copyright 2014 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
: ${CACHE_OPTS=--no-cache}
: ${BOARDS=beaglebone}

# build the base image
docker build ${CACHE_OPTS} -t cros-sdk .
# create the chroot
ID=$(docker run -d --privileged cros-sdk --create)
docker logs -f ${ID}
docker wait ${ID}
# tag the cros-sdk image
docker commit ${ID} cros-sdk

for board in ${BOARDS}; do
    # build the variant
    ID=$(docker run -d --privileged cros-sdk -- ./setup_board --board=$board)
    docker logs -f ${ID}
    docker wait ${ID}
    docker commit ${ID} cros-sdk:$board
    ID=$(docker run -d --privileged cros-sdk -- ./build_packages --board=$board --nowithtest --nowithautotest --nowithfactory)
    docker logs -f ${ID}
    docker wait ${ID}
    # tag the cros-sdk variant
    docker commit ${ID} cros-sdk:$board
done
